export { default as Carousel } from './Carousel'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as ListGenres } from './ListGenres'
export { default as Player } from './Player'
